apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test-daemon
  labels:
    app: npm
spec:
  selector:
    matchLabels:
      app: npm
  template:
    metadata:
      name: test-daemon
      labels:
        app: npm
    spec:
      containers:
        - name: test-daemon
          image: spinkube.azurecr.io/hellodemo
          ports:
            - containerPort: 80
